//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#include <iostream>

int main()
{
    unsigned long long next;
    unsigned long long a = 1;
    unsigned long long b = 2;
    unsigned long long lim = 4000000;
    unsigned long long sumeven = 2;
    while (a + b < lim){
        next = a + b;
        if (next % 2 == 0){
            sumeven += next;
        }
        a = b;
        b = next;
        //std::cout << next << std::endl;
    }
    std::cout << sumeven << std::endl;
    return 0;
}
